worker_processes auto;
error_log /dev/stderr info;
pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    access_log /dev/stdout;
    sendfile on;
    keepalive_timeout 65;

    upstream monitoring_backend {
        server monitoring-backend:8000;
    }

    upstream monitored_service_1 {
        server monitored-service-1:9000;
    }

    upstream monitored_service_2 {
        server monitored-service-2:9000;
    }

    upstream frontend {
        server frontend:80;
    }

    server {
        listen 8080;

        location /api/ {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_pass http://monitoring_backend/;
        }

        location /svc1/ {
            proxy_pass http://monitored_service_1/;
        }

        location /svc2/ {
            proxy_pass http://monitored_service_2/;
        }

        location / {
            proxy_pass http://frontend/;
        }
    }
}
